### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jontstaz** [H256/bf_checker#1]
Hi mate,

Nice script, I was thinking of making my own live BF dashboard since I couldn't find anything like that until now. 

Can you explain the process behind the 'Suggests reduction values for specified Amount of USDT' functionality? It's not quite clear to me from the outset.

The one annoyance I have with the BF API is the 1000 max limit on fetching trades. Adding mongodb could get around this issue by declaring a 'startdate' variable for the first-run of the script. Then it could go back and fetch all data starting from that date and store in DB. From that point on it would just add all new data it fetches to the DB so it would be a complete record. Pagination/date filter on the daily profit table would assist in sorting it properly in the GUI.

A couple other suggestions would be to allow for multiple API keys/accounts and combine the stats.

I will start making some modifications, just wondering if you are currently making changes yourself or have any planned?

Cheers,

**Comment by jontstaz** [comment]
FYI - I have modified the script to accept 2 Binance Futures API keys now. It creates a new DataFrame for the 2nd account and merges the 2 DataFrames into one so dashboard displays combined stats. Not sure if anyone else has a need for this but I like to separate my shorts and longs on diff. accounts.

Will push proposed edit shortly.

**Comment by H256** [comment]
Hi @jontstaz - first of all, thanks for your interest in this small repository. :)

Currently I am not planning to make any changes to the script. But I'll happily accept pull-requests with useful extensions.

About the 'Suggests reduction values for specified Amount of USDT' feature - this is purely experimental. Sometimes I reduce my open positions when they are close to liquidation to prevent exactly that. That's the reason for this little calculator, which calculates how much reduction I have to make on a position to reduce the margin sufficiently. So you don't necessarily need that if you are not as lazy as I am ;)

**Comment by jontstaz** [comment]
No worries mate! I've just made a pull req. for ability to handle up to 3 Binance Futures accounts now. Working on a few other tweaks too.
